version: 2.3.{build}
image: Visual Studio 2017
skip_tags: true
configuration: Release
environment:
  APPVEYOR_BLOCK_DOTNETCORE_TESTS_AUTORUN: true
build_script:
- ps: >-
    $assemblyVersion = ${env:APPVEYOR_BUILD_VERSION}

    $packageVersion = ${env:APPVEYOR_BUILD_VERSION}

    if ($env:APPVEYOR_REPO_BRANCH -ne "master") {
        $packageVersion = "$packageVersion-alpha"
    }

    dotnet build .\Src\HoneyBear.HalClient.sln `
        -c $env:CONFIGURATION `
        -p:AssemblyVersion=$assemblyVersion `
        -p:FileVersion=$assemblyVersion `
        -p:PackageVersion=$packageVersion `
        -p:Version=$packageVersion `
        -p:packageoutputpath=$pwd\artifacts
after_test:
- ps: >-
    . $env:USERPROFILE\.nuget\packages\OpenCover\4.6.519\tools\OpenCover.Console.exe `
        -register:Path64 `
        -filter:"+[HoneyBear.HalClient]*" `
        -target:"$env:USERPROFILE\.nuget\packages\NUnit.ConsoleRunner\3.8.0\tools\nunit3-console.exe" `
        -targetargs:".\Src\HoneyBear.HalClient.Unit.Tests\bin\$env:CONFIGURATION\net471\HoneyBear.HalClient.Unit.Tests.dll" `
        -output:coverage.xml

    . $env:USERPROFILE\.nuget\packages\coveralls.io\1.4.2\tools\coveralls.net.exe `
        --opencover coverage.xml `
        --repo-token hOBugtrP7A2crVX8BA0cT9E8GjnlK8bcP
deploy: off
artifacts:
- path: .\artifacts\*.nupkg
